version: '3'

networks:
  monitoring:
    driver: bridge

services:
  products-service:
    build: ./products-service
    container_name: products-service
    ports:
      - "5001:5001"
    networks:
      - monitoring

  orders-service:
    build: ./orders-service
    container_name: orders-service
    ports:
      - "5002:5002"
    networks:
      - monitoring

  users-service:
    build: ./users-service
    container_name: users-service
    ports:
      - "5003:5003"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
